name: Upload to S3

on:
  push:
    branches:
      - main
    paths:
      - 'Siperb-Provisioning.min.js'
      - 'Siperb-Provisioning.umd.js'
      - 'Siperb-Provisioning.esm.js'

jobs:
  upload-to-s3:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1

      - name: Upload distributable files to S3
        run: |
          VERSION=$(cat VERSION)
          aws s3 cp Siperb-Provisioning.min.js s3://cdn.siperb.com/lib/Siperb-Provisioning/Siperb-Provisioning-${VERSION}.min.js --acl public-read --cache-control "max-age=2628000"
          aws s3 cp Siperb-Provisioning.umd.js s3://cdn.siperb.com/lib/Siperb-Provisioning/Siperb-Provisioning-${VERSION}.umd.js --acl public-read --cache-control "max-age=2628000"
          aws s3 cp Siperb-Provisioning.esm.js s3://cdn.siperb.com/lib/Siperb-Provisioning/Siperb-Provisioning-${VERSION}.esm.js --acl public-read --cache-control "max-age=2628000"
